.db    $00 $00 $00 $00
.db    $00 $00 $00 $00
.db    $00 $00 $00 $00
.db    $00 $00 $00 $00
.db    $00 $00 $00 $00
.db    $00 $00 $00 $00
.db    $00 $00 $00 $00
.db    $00 $00 $00 $00 

.db    $FF $00 $00 $00
.db    $FF $00 $00 $00
.db    $FF $00 $00 $00
.db    $FF $00 $00 $00
.db    $FF $00 $00 $00
.db    $FF $00 $00 $00
.db    $FF $00 $00 $00
.db    $FF $00 $00 $00 

.db    $00 $FF $00 $00
.db    $00 $FF $00 $00
.db    $00 $FF $00 $00
.db    $00 $FF $00 $00
.db    $00 $FF $00 $00
.db    $00 $FF $00 $00
.db    $00 $FF $00 $00
.db    $00 $FF $00 $00 

.db    $FF $FF $00 $00
.db    $FF $FF $00 $00
.db    $FF $FF $00 $00
.db    $FF $FF $00 $00
.db    $FF $FF $00 $00 
.db    $FF $FF $00 $00
.db    $FF $FF $00 $00
.db    $FF $FF $00 $00

.db    $00 $00 $FF $00
.db    $00 $00 $FF $00
.db    $00 $00 $FF $00
.db    $00 $00 $FF $00
.db    $00 $00 $FF $00
.db    $00 $00 $FF $00
.db    $00 $00 $FF $00
.db    $00 $00 $FF $00 

.db    $FF $00 $FF $00
.db    $FF $00 $FF $00
.db    $FF $00 $FF $00
.db    $FF $00 $FF $00
.db    $FF $00 $FF $00
.db    $FF $00 $FF $00
.db    $FF $00 $FF $00
.db    $FF $00 $FF $00 

.db    $00 $FF $FF $00
.db    $00 $FF $FF $00
.db    $00 $FF $FF $00
.db    $00 $FF $FF $00
.db    $00 $FF $FF $00
.db    $00 $FF $FF $00
.db    $00 $FF $FF $00
.db    $00 $FF $FF $00 

.db    $FF $FF $FF $00
.db    $FF $FF $FF $00
.db    $FF $FF $FF $00
.db    $FF $FF $FF $00
.db    $FF $FF $FF $00
.db    $FF $FF $FF $00
.db    $FF $FF $FF $00
.db    $FF $FF $FF $00 

.db    $00 $00 $00 $FF
.db    $00 $00 $00 $FF
.db    $00 $00 $00 $FF
.db    $00 $00 $00 $FF
.db    $00 $00 $00 $FF
.db    $00 $00 $00 $FF
.db    $00 $00 $00 $FF
.db    $00 $00 $00 $FF 

.db    $FF $00 $00 $FF
.db    $FF $00 $00 $FF
.db    $FF $00 $00 $FF
.db    $FF $00 $00 $FF
.db    $FF $00 $00 $FF
.db    $FF $00 $00 $FF
.db    $FF $00 $00 $FF
.db    $FF $00 $00 $FF

; 10
.db    $00 $FF $00 $FF
.db    $00 $FF $00 $FF
.db    $00 $FF $00 $FF
.db    $00 $FF $00 $FF
.db    $00 $FF $00 $FF
.db    $00 $FF $00 $FF
.db    $00 $FF $00 $FF
.db    $00 $FF $00 $FF

.db    $FF $FF $00 $FF
.db    $FF $FF $00 $FF
.db    $FF $FF $00 $FF
.db    $FF $FF $00 $FF
.db    $FF $FF $00 $FF
.db    $FF $FF $00 $FF
.db    $FF $FF $00 $FF
.db    $FF $FF $00 $FF

.db    $00 $00 $FF $FF
.db    $00 $00 $FF $FF
.db    $00 $00 $FF $FF
.db    $00 $00 $FF $FF
.db    $00 $00 $FF $FF
.db    $00 $00 $FF $FF
.db    $00 $00 $FF $FF
.db    $00 $00 $FF $FF

.db    $FF $00 $FF $FF
.db    $FF $00 $FF $FF
.db    $FF $00 $FF $FF
.db    $FF $00 $FF $FF
.db    $FF $00 $FF $FF
.db    $FF $00 $FF $FF
.db    $FF $00 $FF $FF
.db    $FF $00 $FF $FF

.db    $00 $FF $FF $FF
.db    $00 $FF $FF $FF
.db    $00 $FF $FF $FF
.db    $00 $FF $FF $FF
.db    $00 $FF $FF $FF
.db    $00 $FF $FF $FF
.db    $00 $FF $FF $FF
.db    $00 $FF $FF $FF

.db    $FF $FF $FF $FF
.db    $FF $FF $FF $FF
.db    $FF $FF $FF $FF
.db    $FF $FF $FF $FF
.db    $FF $FF $FF $FF
.db    $FF $FF $FF $FF
.db    $FF $FF $FF $FF
.db    $FF $FF $FF $FF